export const defaultCategories = [
  "Meals & Entertainment",
  "Travel (Airfare)",
  "Travel (Lodging)",
  "Travel (Ground Transport)",
  "Fuel & Mileage",
  "Office Supplies",
  "Software & Subscriptions",
  "Telecommunications",
  "Marketing & Advertising",
  "Professional Services",
  "Shipping & Postage",
  "Training & Education",
  "Equipment & Hardware",
  "Utilities",
  "Rent & Facilities",
  "Taxes & Fees",
  "Insurance",
  "Miscellaneous",
];
